### ISSUE TITLE
AndHUD exception in Android 5.0.1 (API21) ?

### ISSUE THREAD

**Issue by jeromeliger** [Redth/AndHUD#17]
Hi,

I've been using AndHud in my production application since yet with no problems and an amazing facility... thanks for your work first !

But I've made an update of my solution to target Android 5.0.1 (my test device GalasyS4 has been updated), and I got a problem...

It seems to happens at " AndroidHUD.AndHUD.ShowStatus" that was working until this update of target version.

Does anybody have this problem with Android API 21 ? is AndHUD compatible ?

EDIT : apparently this happens only in debug, not in release... maybe my configuration ?

This is my (very simple) call :

AndHUD.Shared.Show(_act, null, -1, MaskType.Clear, default(TimeSpan?), null, true, null);

And this is the stacktrace of the error :

System.Diagnostics.Debugger.Mono_UnhandledException_internal () in 
System.Diagnostics.Debugger.Mono_UnhandledException (ex={Java.Lang.RuntimeException: Exception of type 'Java.Lang.RuntimeException' was thrown.

  --- End of managed exception stack trace ---
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
	... 1 more
Caused by: md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
at Android.Runtime.JNIEnv.<Initialize>m__0 (intptr) <IL 0x0000b, 0x00080>
at Java.Lang.Object.GetObject (intptr,Android.Runtime.JniHandleOwnership,System.Type) <IL 0x0002d, 0x001c7>
at Java.Lang.Object._GetObject<Android.Views.Window> (intptr,Android.Runtime.JniHandleOwnership) <0x00107>
at Java.Lang.Object.GetObject<Android.Views.Window> (intptr,Android.Runtime.JniHandleOwnership) <0x0006f>
at Android.App.Dialog.get_Window () <IL 0x00054, 0x00203>
at AndroidHUD.AndHUD/<SetupDialog>c__AnonStorey3.<>m__0 (object) <IL 0x00040, 0x00177>
at Android.App.SyncContext.Send (System.Threading.SendOrPostCallback,object) <IL 0x00031, 0x0019b>
at AndroidHUD.AndHUD.SetupDialog (Android.Content.Context,AndroidHUD.MaskType,System.Action,System.Func`4<Android.Content.Context, Android.App.Dialog, AndroidHUD.MaskType, Android.Views.View>) <IL 0x0003d, 0x00243>
at AndroidHUD.AndHUD.showStatus (Android.Content.Context,bool,string,AndroidHUD.MaskType,System.Nullable`1<System.TimeSpan>,System.Action,bool,System.Action) <IL 0x000cd, 0x0068b>
at AndroidHUD.AndHUD.Show (Android.Content.Context,string,int,AndroidHUD.MaskType,System.Nullable`1<System.TimeSpan>,System.Action,bool,System.Action) <IL 0x0002c, 0x0021b>
at Kiosk_Android.Activity_Web/HelloWebViewClient.OnPageStarted 

Thanks for return.

Jérôme

**Comment by Nyakoo** [comment]
Did you find a solution for this or an alternative?

**Comment by jeromeliger** [comment]
Yes, as I supposed it was my configuration...
So I set-up a new environment with latest VS/Xamarin, I load my project and all was OK.
No bug / relation with AndHUD.
